/*
 * File: xds_index.js
 * Date: Fri Jan 01 2010 00:08:58 GMT-0500 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new winLogIn({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
