/*
 * File: winLogIn.ui.js
 * Date: Fri Jan 01 2010 00:08:58 GMT-0500 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

winLogInUi = Ext.extend(Ext.Window, {
    title: 'Iniciar sesión',
    width: 306,
    height: 117,
    modal: true,
    closable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                title: '',
                height: 140,
                frame: true,
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Usuario',
                        anchor: '100%',
                        id: 'user'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Contraseña',
                        anchor: '100%',
                        inputType: 'password',
                        id: 'passwd'
                    },
                    {
                        xtype: 'compositefield',
                        fieldLabel: 'Servidor',
                        anchor: '100%',
                        items: [
                            {
                                xtype: 'textfield',
                                flex: 1,
                                fieldLabel: 'Label'
                            },
                            {
                                xtype: 'numberfield',
                                flex: 1,
                                fieldLabel: 'Label'
                            }
                        ]
                    }
                ]
            }
        ];
        winLogInUi.superclass.initComponent.call(this);
    }
});
