/*
 * File: winLogIn.js
 * Date: Fri Jan 01 2010 00:08:58 GMT-0500 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

winLogIn = Ext.extend(winLogInUi, {
    initComponent: function() {
        winLogIn.superclass.initComponent.call(this);
    }
});
